config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'home#index'

  get 'home' => "home#index", as: :home
  get 'sobre-a-empresa' => "pages#about", as: :about
  get 'divulgacoes-e-parcerias' => "pages#advertising", as: :advertising
  get 'fale-conosco' => "contact#index", as: :contact
  post 'enviar-contato' => "contact#send_contact", as: :send_contact

  resources :teams, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :races, except: :show do
    member do
      get :send_notifications
    end
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :products, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :posts, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :post_categories
  resources :public_products, only: :show, path: :produtos
  resources :public_post_categories, only: :show, path: 'posts-por-categoria'
  resources :public_races, only: [:index, :show], path: 'provas', path_names: {calendar: 'calendario', last: 'ultimos-resultados', race_organization: 'organize-sua-prova', send_contact: 'enviar-mensagem'} do
    collection do
      get :calendar
      get :last
      get :race_organization
      post :send_contact
    end
  end
  resources :public_teams, only: [:index, :show], path: 'equipes', path_names: {special: 'oficiais'} do
    collection do
      get :special
    end
  end
  get 'posts/:id' => 'public_posts#show', as: :public_post
  resources :public_robberies, path: 'furtos', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }
  resources :public_suspicions, path: 'suspeitas', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }

  get 'minha-conta' => 'my_account#index', as: :my_account
  put 'atualizar-minha-conta' => 'my_account#update', as: :update_my_account

end

app/models/race.rb
class Race < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  attr_accessor :race_picture

  belongs_to :user
  has_many :pictures, as: :imageable, dependent: :destroy

  validates :user_id, :title, :resume, :description, :contact, :contact_phone, :race_details,
  :occur_at, :registration_start_at, :registration_end_at, :zipcode, :state, :city, :address,
  :payment_method, :payment_details, presence: true
  validates :race_picture, presence: true, on: :create

  def picture
    @picture ||= begin
      race_picture = pictures.where(master: true).first
      race_picture.try(:photo)
    end
  end

  after_save do
    if self.race_picture
      if race_picture_ziped?
        save_race_pictures_in_zip
      else
        save_race_picture_image
      end
    end
  end

  after_create do
    if self.send_notifications && !self.occured?
      User.where(send_races: true).each do |user|
        RaceMailer.delay.new_race(user, self)
      end
    end
  end

  def notify!
    User.where(send_races: true).each do |user|
      RaceMailer.delay.new_race(user, self)
    end
  end

  def occured?
    self.occur_at < Date.today
  end

  def race_picture_ziped?
    File.extname(self.race_picture.path).downcase.include?("zip")
  end

  def save_race_picture_image
    Picture.transaction do
      self.pictures.update_all(master: false)
      self.pictures.build(master: true, photo: self.race_picture).save!
    end
  end

  def save_race_pictures_in_zip
    require 'zip'
    Zip::File.open(self.race_picture.path) do |zipfile|
      zipfile.each do |file|
        next if file.directory? || File.basename(file.name)[0..1] == "._"
        tempfile_path = Rails.root.join('tmp', File.basename(file.name))
        zipfile.extract(file, tempfile_path.to_s) unless File.exist?(tempfile_path)

        picture = self.pictures.build(photo: File.open(tempfile_path), master: false)
        picture.save(validate: false)

        File.unlink(tempfile_path)
      end
    end
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_race, only: [:show, :edit, :update, :destroy, :send_notifications]

  # GET /races
  # GET /races.json
  def index
    @races = Race.order(occur_at: :desc)
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
    10.times do
      @race.pictures.build
    end
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to public_race_path(@race), notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to public_race_path(@race), notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_notifications
    @race.notify!
    redirect_to :back, notice: 'Notificações sendo enviadas'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params[:race].permit(:user_id, :title, :resume, :description, :race_type, :organization,
        :contact, :contact_phone, :contact_mobile, :contact_email, :race_details, :occur_at,
        :registration_start_at, :registration_end_at, :state, :city, :address, :zipcode, :video,
        :payment_method, :payment_details, :race_picture, :show_title_in_index, :send_notifications)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= simple_form_for(@race, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="well">
    <div class="row">
      <h3>Descrição da Prova</h3>
      <div class="col-sm-12">
        <%= f.association :user, collection: User.all, label_method: :email %>
      </div>
      <div class="col-sm-12">
        <%= f.input :title %>
      </div>
      <div class="col-sm-12">
        <%= f.input :show_title_in_index %>
      </div>
      <div class="col-sm-12">
        <%= f.input :video %>
      </div>
      <div class="col-sm-12">
        <%= f.input :race_picture, as: :file %>
      </div>
      <% if f.object.picture %>
      <div>
        <%= image_tag f.object.picture.url(:medium) %>
      </div>
      <% end -%>
      <div class="col-sm-12">
        <%= f.input :resume %>
      </div>
      <div class="col-sm-12">
        <%= f.input :description, input_html: {rows: 5} %>
      </div>
      <div class="col-sm-12">
        <%= f.input :race_type %>
      </div>
      <div class="col-sm-12">
        <%= f.input :send_notifications %>
      </div>
    </div>
  </div>
  <div class="well">
    <div class="row">
      <h3>Organização e Contato</h3>
      <div class="col-sm-12">
        <%= f.input :organization %>
      </div>
      <div class="col-sm-12">
        <%= f.input :contact %>
      </div>
      <div class="col-sm-12">
        <%= f.input :contact_phone %>
      </div>
      <div class="col-sm-12">
        <%= f.input :contact_mobile %>
      </div>
      <div class="col-sm-12">
        <%= f.input :contact_email %>
      </div>
    </div>
  </div>
  <div class="well">
    <div class="row">
      <h3>Planejamento</h3>
      <div class="col-sm-12">
        <%= f.input :race_details, input_html: {rows: 5} %>
      </div>
      <div class="col-sm-12">
        <%= f.input :occur_at %>
      </div>
      <div class="col-sm-12">
        <%= f.input :registration_start_at %>
      </div>
      <div class="col-sm-12">
        <%= f.input :registration_end_at %>
      </div>
    </div>
  </div>
  <div class="well">
    <div class="row">
      <h3>Localização</h3>
      <div class="col-sm-12">
        <%= f.input :zipcode %>
      </div>
      <div class="col-sm-12">
        <%= f.input :state %>
      </div>
      <div class="col-sm-12">
        <%= f.input :city %>
      </div>
      <div class="col-sm-12">
        <%= f.input :address %>
      </div>
    </div>
  </div>
  <div class="well">
    <div class="row">
      <h3>Informações de Pagamento</h3>
      <div class="col-sm-12">
        <%= f.input :payment_method %>
      </div>
      <div class="col-sm-12">
        <%= f.input :payment_details, input_html: {rows: 5} %>
      </div>
    </div>
  </div>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to(t('manage_pictures'), race_pictures_path(@race), class: 'btn btn-primary') unless @race.new_record? %>
  <%= link_to 'Voltar', races_path, class: 'btn btn-default' %>
<% end %>

app/views/races/edit.html.erb
<section class="container padding-bottom">
  <%= title_for_create_update(:edit, :race) %>

  <%= render 'form' %>
</section>

app/views/races/index.html.erb
<section class="container padding-bottom">

<%= title_for_list(:race) %>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Título</th>
      <th>Data</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.id %></td>
        <td><%= race.title %></td>
        <td><%= l race.occur_at %></td>
        <td><%= link_to 'Enviar Notificação', send_notifications_race_path(race) %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>
</section>

app/views/races/new.html.erb
<section class="container padding-bottom">
  <%= title_for_create_update(:create, :race) %>

  <%= render 'form' %>
</section>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>