config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'home#index'

  get 'home' => "home#index", as: :home
  get 'sobre-a-empresa' => "pages#about", as: :about
  get 'divulgacoes-e-parcerias' => "pages#advertising", as: :advertising
  get 'fale-conosco' => "contact#index", as: :contact
  post 'enviar-contato' => "contact#send_contact", as: :send_contact

  resources :teams, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :races, except: :show do
    member do
      get :send_notifications
    end
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :products, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :posts, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :post_categories
  resources :public_products, only: :show, path: :produtos
  resources :public_post_categories, only: :show, path: 'posts-por-categoria'
  resources :public_races, only: [:index, :show], path: 'provas', path_names: {calendar: 'calendario', last: 'ultimos-resultados', race_organization: 'organize-sua-prova', send_contact: 'enviar-mensagem'} do
    collection do
      get :calendar
      get :last
      get :race_organization
      post :send_contact
    end
  end
  resources :public_teams, only: [:index, :show], path: 'equipes', path_names: {special: 'oficiais'} do
    collection do
      get :special
    end
  end
  get 'posts/:id' => 'public_posts#show', as: :public_post
  resources :public_robberies, path: 'furtos', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }
  resources :public_suspicions, path: 'suspeitas', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }

  get 'minha-conta' => 'my_account#index', as: :my_account
  put 'atualizar-minha-conta' => 'my_account#update', as: :update_my_account

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.actives.order(created_at: :desc).limit(10)
    @race_special = Race.order("occur_at desc").first
    @races = Race.where("id <> ?", @race_special.try(:id)).order(occur_at: :desc).limit(3)
    @team = Team.where(special: true).order("rand()").first
    @post = Post.actives.ordered.first
  end

  def invite_user
    User.invite!(:email => params[:email])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_post.erb
<% if @post %>
<!--Central Content-->
<section class="container top">
    <div class="row">
        <div class="col-md-12 item-category post events full-width">
            <%= render "public_post_categories/post", post: @post %>
            <div class="divider"></div>
        </div>

    </div>
</section>
<!--Central Content-->
<% end -%>

app/views/home/_races.erb
<% if @race_special %>
<!-- Video -->
<section class="container">
    <div class="row">
        <div class="col-lg-12 top-mini">
        <h2 class="center">Próxima <span class="color">Prova</span> e tudo que já ocorreu</h2>
        <hr />
        </div>
    </div>
</section>
<section class="video-gallery top-mini">
    <% unless @race_special.video.blank? %>
    <a class="iframe_video" title="<%= @race_special.title %>" href="https://www.youtube.com/embed/<%= @race_special.video %>?autoplay=1">
            <div class="video">
                <figure>
                    <ul class="rslides">
                      <li><%= image_tag @race_special.picture.url %></li>
                  </ul>
                  <figcaption>
                    <div class="wow pulse animated" data-wow-delay="300ms" data-wow-iteration="infinite" data-wow-duration="2s">
                        <i class="fa fa-play-circle"></i>
                    </div>
                    <% if @race_special.show_title_in_index %>
                    <div class="text-video">
                        <h2><%= @race_special.title %></h2>
                        <time datetime="<%= @race_special.occur_at.to_s(:db) %>"><%= l @race_special.occur_at %></time>
                    </div>
                    <div class="sub-text wow fadeInRight animated" data-wow-delay="300ms" data-wow-duration="2s">
                        <h4>Em destaque</h4>
                    </div>
                    <% end -%>
                </figcaption>
            </figure>
        </div>
    </a>
    <% else %>
    <a href="<%= public_race_path(@race_special) %>">
      <div class="video">
        <figure>
          <ul class="rslides">
            <li><%= image_tag @race_special.picture.url %></li>
          </ul>
          <figcaption>
            <% if @race_special.show_title_in_index %>
            <div class="text-video">
              <h2><%= @race_special.title %></h2>
              <time datetime="<%= @race_special.occur_at.to_s(:db) %>"><%= l @race_special.occur_at %></time>
            </div>
            <div class="sub-text wow fadeInRight animated" data-wow-delay="300ms" data-wow-duration="2s">
              <h4>Em destaque</h4>
            </div>
            <% end -%>
          </figcaption>
        </figure>
      </div>
    </a>
    <% end -%>


<div class="row gallery" style="margin-top:0">

    <!--Items-->
    <% @races.each do |race| %>
    <div class="col-md-12">
        <h3><%= link_to race.title, public_race_path(race) %></h3>
        <hr />
        <p><small><i class="fa fa-calendar"></i> <%= t('.occur_at') %>: <%= l(race.occur_at, format: :short) %></small></p>
        <p><%= race.resume %></p>
    </div>
    <!--Items-->
        <% if race.pictures.count > 1 %>
        <!--Gallery Images-->
        <div class="col-md-12">
            <ul class="gallery-images top">
                <% race.pictures.limit(8).order("rand()").each do |picture| %>
                <li>
                    <a class="fancybox center"  title="" href="<%= picture.photo.url(:big) %>">
                        <figure><img src="<%= picture.photo.url(:gallery_list) %>" alt=""><figcaption><i class="fa fa-search-plus"></i></figcaption></figure>
                    </a>
                </li>
                <% end -%>
            </ul>
        </div>
        <!--Gallery Images-->
        <% end -%>
    <% end -%>

</div>

</section>
<!-- Video -->
<% end -%>

app/views/home/_robbery.erb
<!-- Register -->
<section class="bar-section center" style="clear: both">
  <!-- <h1 class="title-downloads">
    <span class="color">Radar Bike</span> já registrou
    <span class="responsive-numbers">
      <span>2</span>
      <span>6</span>
      <span>1</span>
      <span>2</span>
    </span>
    furtos e possíveis soluções.
  </h1> -->

  <div class="container">
    <h2>
      Todo ciclista teme por sua vida e é claro sua bicicleta. Pensamos então em uma maneira de tentar achar nosso bem tão valioso
    </h2>
    <ul>
      <li><strong>01<i class="fa fa-user-plus"></i></strong><span>cria sua conta</span></li>
      <li><strong>02<i class="fa fa-bicycle"></i></strong><span>registre o furto</span></li>
      <li><strong>03<i class="fa fa-search"></i></strong><span>aguarde o radar</span></li>

    </ul>
  </div>
</section>
<!-- Register -->

app/views/home/_selling.erb
<% unless @products.blank? %>
<!--VENDAS-->
<section class="container display-pc">
  <div class="row">
    <div class="col-lg-12 top-mini">

      <h2 class="center">Ofertas em <span class="color">Destaque</span> e com <span class="color">Ótimos Preços</span></h2>
      <hr>

      <ul class="carousel-bikes center">
        <% @products.each do |product| %>
        <!--Item-->
        <li>
          <div class="image-bike">
            <%= image_tag product.picture.url(:medium), alt: product.name %>
          </div>
          <div class="text-bike">
            <a href="<%= public_product_path(product) %>"><h4><%= product.name %></h4></a>
            <p><span class="color">preço:</span> <%= product_price(product) %></p>
          </div>
        </li>
        <!--Item-->
        <% end -%>

      </ul>
    </div>
  </div>
</section>
<!--VENDAS FIM-->
<% end -%>

app/views/home/_team.erb
<% if @team %>
<!-- equipe em destaque -->
<section class="container padding-bottom display-pc">

    <div class="row">

      <!--First Team-->
        <div class="col-md-12 right">
                        <h2 class="center">Equipe em destaque: <%= @team.name %></h2>
                    <hr>
                        <ul class="team-carousel">
                        <li>
                        <figure class="team-gallery">
                            <%= image_tag (@team.picture.blank? ? 'team/team-01.jpg' : @team.picture.url(:team_list)) %>

                            <figcaption class="overlay-info">

                                <div class="data-name">
                                    <h3><%= @team.name %></h3>
                                </div>

                                <div class="overlay-description">
                                   <%= truncate @team.description, length: 100 %>
                                </div>

                            </figcaption>

                        </figure>
                        </li>
                        <% @team.team_members.limit(4).order("rand()").each do |team_member| %>
                         <li>
                            <figure class="team-gallery">
                                <%= image_tag (team_member.photo_file_name.blank? ? 'team/team-01.jpg' : team_member.photo.url(:team_list)) %>

                                <figcaption class="overlay-info">

                                    <div class="data-name">
                                        <h3><%= team_member.member %></h3>
                                    </div>

                                    <div class="overlay-description">
                                       <%= simple_format team_member.resume %>
                                    </div>

                                </figcaption>

                            </figure>
                            </li>
                        <% end %>
                        </ul>
                        <%= link_to 'Mais informações', public_team_path(@team), class: 'btn btn-primary' %>
                    </div>
        <!--First Team-->
    </div>
</section>
<!-- equipe em destaque FIM -->
<% end -%>

app/views/home/index.html.erb
<%= render "races" %>
<%= render "robbery" %>
<%= render "selling" %>
<%= render "post" %>
<%= render "team" %>