config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'home#index'

  get 'home' => "home#index", as: :home
  get 'sobre-a-empresa' => "pages#about", as: :about
  get 'divulgacoes-e-parcerias' => "pages#advertising", as: :advertising
  get 'fale-conosco' => "contact#index", as: :contact
  post 'enviar-contato' => "contact#send_contact", as: :send_contact

  resources :teams, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :races, except: :show do
    member do
      get :send_notifications
    end
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :products, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :posts, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :post_categories
  resources :public_products, only: :show, path: :produtos
  resources :public_post_categories, only: :show, path: 'posts-por-categoria'
  resources :public_races, only: [:index, :show], path: 'provas', path_names: {calendar: 'calendario', last: 'ultimos-resultados', race_organization: 'organize-sua-prova', send_contact: 'enviar-mensagem'} do
    collection do
      get :calendar
      get :last
      get :race_organization
      post :send_contact
    end
  end
  resources :public_teams, only: [:index, :show], path: 'equipes', path_names: {special: 'oficiais'} do
    collection do
      get :special
    end
  end
  get 'posts/:id' => 'public_posts#show', as: :public_post
  resources :public_robberies, path: 'furtos', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }
  resources :public_suspicions, path: 'suspeitas', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }

  get 'minha-conta' => 'my_account#index', as: :my_account
  put 'atualizar-minha-conta' => 'my_account#update', as: :update_my_account

end

app/controllers/public_races_controller.rb
class PublicRacesController < ApplicationController
  before_action :set_race, only: [:show]

  def index
    @races = Race.where("occur_at > ?", Date.today).order(occur_at: :desc).page(params[:page])
  end

  def last
    @races = Race.where("occur_at <= ?", Date.today).order(occur_at: :desc).page(params[:page])
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  def race_organization
    @race_organization_contact = RaceOrganizationContact.new
  end

  def send_contact
    @race_organization_contact = RaceOrganizationContact.new(race_organization_contact_params)
    @race_organization_contact.subject = 'Novo interesse em organização de prova'
    if @race_organization_contact.deliver
      redirect_to race_organization_public_races_path, success: 'Mensagem enviada com sucesso. Em breve entraremos em contato.'
    else
      flash[:error] = 'Falha ao enviar a mensagem. Todos os campos são obrigatórios'
      render :race_organization
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.friendly.find(params[:id])
    end

    def race_organization_contact_params
      params[:race_organization_contact].permit(:name, :visitor_email, :message, :occur_at, :motive)
    end
end

app/helpers/public_races_helper.rb
module PublicRacesHelper
  def race_organization_message_placeholder
    "Escreva mais informações sobre a prova como:
- Motivo da prova (aniversário da cidade, data comemorativa):
- Data:
- Horário:
- Estilo preferido (speed, montanhas, etc...):

Em breve entraremos em contato"
  end

  def races_events
    Race.where("occur_at >= ?",Date.today.beginning_of_year).map do |race|
      {title: race.title, url: public_race_path(race), start: race.occur_at.strftime("%Y-%m-%d")}
    end.to_json.html_safe
  end
end

app/views/public_races/_race.html.erb
<div class="row item-category events">
  <div class="items">
    <figure class="col-lg-4 col-md-6 col-sm-6">
      <%= image_tag race.picture.url(:medium), alt: race.title %>
      <figcaption>
        <h4><%= race.city %> / <%= race.state %></h4>
        <hr>
        <p><%= race.race_type %></p>
        <a class="btn btn-primary" href="<%= public_race_path(race) %>" role="button">Mais informações</a>
      </figcaption>
    </figure>
  </div>

  <div class="col-lg-3 details col-md-6 col-sm-6">
    <h4><i class="fa fa-calendar"></i> Inscrição</h4>
    <p><%= race.payment_method %></p>

    <div class="top-mini">
      <h4><i class="fa fa-money"></i> Dados para pagamento</h4>
      <p><%= simple_format race.payment_details %></p>
    </div>

    <div class="top-mini">
      <h4><i class="fa fa-clock-o"></i> Data de realização</h4>
      <p><%= l(race.occur_at) %></p>
    </div>
  </div>

  <div class="col-lg-5 col-md-12 description col-sm-12">
    <h4><%= race.title %></h4>
    <hr class="left-hr">
    <p><%= simple_format race.resume %></p>
  </div>
</div>

app/views/public_races/_race_full_detail.html.erb
<div class="row item-category events">
  <div class="items">
    <figure class="col-lg-4 col-md-6 col-sm-6">
      <%= image_tag race.picture.url(:medium), alt: race.title %>
      <figcaption>
        <h4><%= race.city %> / <%= race.state %></h4>
        <hr>
        <p><%= race.race_type %></p>
        <a class="btn btn-primary" href="<%= public_race_path(race) %>" role="button">Mais informações</a>
      </figcaption>
    </figure>
  </div>

  <div class="col-lg-3 details col-md-6 col-sm-6">
    <h4><i class="fa fa-calendar"></i> Inscrição</h4>
    <p><%= race.payment_method %></p>

    <div class="top-mini">
      <h4><i class="fa fa-money"></i> Dados para pagamento</h4>
      <p><%= simple_format race.payment_details %></p>
    </div>

    <div class="top-mini">
      <h4><i class="fa fa-clock-o"></i> Data de realização</h4>
      <p><%= l(race.occur_at) %></p>
    </div>
  </div>

  <div class="col-lg-5 col-md-12 description col-sm-12">
    <h4><%= race.title %></h4>
    <hr class="left-hr">
    <p><%= simple_format race.description %></p>
  </div>
</div>

app/views/public_races/calendar.html.erb
<!--Background Image title-->
<section class="bg-title">
  <!-- <img src="/assets/titles-zones/title-zone-02.jpg" alt=""> -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row text-content paddings center">
      <div class="col-md-12">
        <h2><%= t('.title') %></h2>
      </div>
    </div>
  </div>
</section>
<!--Background Image title-->
<!--Central Content-->
<section class="container padding-bottom">
  <div class="top-mini">
    <div id='calendar'></div>
  </div>
</section>
<!--Central Content-->
<%= content_for :footer do %>
<%= javascript_include_tag 'fullcalendar-2.4.0/moment', 'data-turbolinks-track' => true %>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.4.0/fullcalendar.min.js"></script>
<%= javascript_include_tag 'fullcalendar-2.4.0/lang/pt-br', 'data-turbolinks-track' => true %>
<link rel="stylesheet" media="all" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.4.0/fullcalendar.min.css" data-turbolinks-track="true">
<script type="text/javascript">
  $(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'month,basicWeek,basicDay'
        },
        events: <%=races_events %>
    })

});
</script>
<% end -%>

app/views/public_races/index.html.erb
<!--Background Image title-->
<section class="bg-title">
  <!-- <img src="/assets/titles-zones/title-zone-02.jpg" alt=""> -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row text-content paddings center">
      <div class="col-md-12">
        <h2><%= t('.title') %></h2>
      </div>
    </div>
  </div>
</section>
<!--Background Image title-->
<!--Central Content-->
<section class="container">
  <div class="top-mini">
    <% unless @races.blank? %>
    <% @races.each do |race| %>
    <%= render 'race', race: race %>
    <div class="divider"></div>
    <% end -%>

    <%= paginate @races %>
    <% else %>
    <div class="padding-bottom">
      <h2>Opa, não existem provas a acontecer</h2>
      <p>Isso é algo raro de acontecer mas pode ser que não tenhamos provas a serem exibidas. Neste caso talvez você queira:</p>
      <ul>
        <li>Cadastrar uma nova prova (em breve)</li>
        <li><%= link_to 'Conferir as provas que aconteceram', last_public_races_path %></li>
      </ul>
    </div>
    <% end -%>

  </div>
</section>
<!--Central Content-->

app/views/public_races/last.html.erb
<!--Background Image title-->
<section class="bg-title">
  <!-- <img src="/assets/titles-zones/title-zone-02.jpg" alt=""> -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row text-content paddings center">
      <div class="col-md-12">
        <h2><%= t('.title') %></h2>
      </div>
    </div>
  </div>
</section>
<!--Background Image title-->
<!--Central Content-->
<section class="container">
  <div class="top-mini">
    <% unless @races.blank? %>
    <% @races.each do |race| %>
    <%= render 'race', race: race %>
    <div class="divider"></div>
    <% end -%>

    <%= paginate @races %>
    <% else %>
    <div class="padding-bottom">
      <h2>Opa, não existem provas registradas</h2>
      <p>Isso é algo raro de acontecer mas pode ser que não tenhamos provas a serem exibidas. Neste caso talvez você queira:</p>
      <ul>
        <li>Cadastrar uma nova prova (em breve)</li>
        <li><%= link_to 'Conferir as próximas provas', public_races_path %></li>
      </ul>
    </div>
    <% end -%>

  </div>
</section>
<!--Central Content-->

app/views/public_races/race_organization.html.erb
<!--Background Image title-->
<section class="bg-title">
  <!-- <img src="/assets/titles-zones/title-zone-02.jpg" alt=""> -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row text-content paddings center">
      <div class="col-md-12">
        <h2>Quer uma prova de ciclismo em sua cidade?</h2>
      </div>
    </div>
  </div>
</section>
<!--Background Image title-->

<!--Central Content-->
<section class="container">
  <div class="row paddings place-purchase">
    <div class="col-lg-12">
      <p>Organizar uma prova de ciclismo exige tempo, experiência e um histórico de eventos de qualidade.</p>
      <p>Para isso temos uma parceria com Erick Fênix MTB que organiza provas mineiras. A experiência com eventos fará com que a prova em sua cidade possa ser organizada com:</p>
      <ul>
        <li>Segurança</li>
        <li>Qualidade</li>
        <li>Divulgação para diversos atletas</li>
        <li>Trará incentivo para a população para a prática do esporte</li>
      </ul>
    </div>
    <div class="col-lg-6 item-category col-md-6 col-sm-12">
      <!--item where buy-->
      <figure class="items">
        <img src="/assets/ContactUs.jpg" alt="">
        <figcaption>
          <div class="center">
            <h4 class="text-uppercase">Sobre Erick Fênix MTB</h4>
            <hr />
            <p>Mais informações sobre nosso parceiro de organização de provas.</p>
          </div>
          <ul class="working-hours">
            <li><p>Telefone <span>(31) 7520-4516 | (61) 8183-7048</span></p></li>
            <li><p>Facebook <span><%= link_to 'fenixmtbesportesradicais', 'https://www.facebook.com/fenixmtbesportesradicais?fref=ts', target: '_blank' %></span></p></li>
            <li><p>Skype <span>SITERADARBIKE</span></p></li>
          </ul>
        </figcaption>
      </figure>
      <!--item where buy-->

    </div>

    <!--Contact Form-->
    <div class="col-lg-6 col-md-6 col-sm-12">

      <h3 class="form-contact">Preencha os campos abaixo para entrar em contato conosco</h3>
      <hr class="left-hr" />

      <%= simple_form_for @race_organization_contact, url: send_contact_public_races_path, html: {class: 'form-contact'} do |f| %>
      <div class="row form-group form-comment form_contact">
        <!--Name-->
        <div class="col-sm-12">
          <%= f.input :name, label: 'Seu nome completo', required: :required %>

        </div>
        <!--Name-->

        <!--email-->
        <div class="col-sm-12">
          <%= f.input :visitor_email, label: 'Seu e-mail', required: :required %>
        </div>
        <!--email-->

        <div class="col-sm-12">
          <%= f.input :motive, label: 'Motivo da prova', required: :required %>
        </div>

        <div class="col-sm-12">
          <%= f.input :occur_at, placeholder: "00/00/0000", label: 'Data', required: :required %>
        </div>

        <!--email-->
        <div class="col-sm-12">
          <%= f.input :message, as: :text, label: 'Descrição', rows: 3, required: :required %>
        </div>
        <!--email-->
      </div>
      <!--Name-->
      <div class="result"></div>
      <button type="submit" class="btn btn-primary">Enviar mensagem</button>
      <% end -%>

    </div>
    <!--Contact Form-->

  </div>
</section>
<!--Central Content-->

app/views/public_races/show.html.erb
<!--Background Image title-->
<section class="bg-title">
  <!-- <img src="/assets/titles-zones/title-zone-02.jpg" alt=""> -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row text-content paddings center">
      <div class="col-md-12">
        <h2><%= @race.title %></h2>
      </div>
    </div>
  </div>
</section>
<!--Background Image title-->
<!--Central Content-->
<section class="container">
  <div class="top-mini padding-bottom">
    <div class="row">
      <div class="col-md-12">
        <%= render 'race_full_detail', race: @race %>
      </div>
    </div>
    <div class="row top-mini">
      <div class="col-md-6">
        <h4>Organização</h4>
        <p><%= @race.organization %></p>

        <div class="top-mini">
          <h4>Contato</h4>
          <p><%= [@race.contact, @race.contact_phone, @race.contact_mobile, @race.contact_email].reject{|t| t.blank?}.join(' - ') %></p>
        </div>

        <div class="top-mini">
          <h4>Data para inscrição</h4>
          <p><%= l(@race.registration_start_at) %> a <%= l(@race.registration_end_at) %></p>
        </div>

        <div class="top-mini">
          <h4>Endereço</h4>
          <p><%= @race.address %> - <%= @race.city %>/<%= @race.state %></p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <h4>Imagens</h4>
            <ul class="gallery-images sidebar">
            <% @race.pictures.all.each do |picture| %>
              <li>
                  <a class="fancybox center" title="" href="<%= picture.photo.url %>">
                    <figure><img src="<%= picture.photo.url(:medium) %>" alt=""><figcaption><i class="fa fa-search-plus"></i></figcaption></figure>
                  </a>
              </li>
            <% end -%>
            </ul>
          </div>
          <% unless @race.video.blank? %>
          <div class="col-md-12 top">
            <iframe width="500" height="315" src="https://www.youtube.com/embed/<%= @race.video %>" frameborder="0" allowfullscreen></iframe>
          </div>
          <% end -%>
        </div>
      </div>
    </div>
    <div class="row top-mini">
      <div class="col-md-12">
        <h4>Detalhes da prova</h4>
        <p><%= simple_format @race.race_details %></p>
      </div>
    </div>
  </div>
</section>
<!--Central Content-->