config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'home#index'

  get 'home' => "home#index", as: :home
  get 'sobre-a-empresa' => "pages#about", as: :about
  get 'divulgacoes-e-parcerias' => "pages#advertising", as: :advertising
  get 'fale-conosco' => "contact#index", as: :contact
  post 'enviar-contato' => "contact#send_contact", as: :send_contact

  resources :teams, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :races, except: :show do
    member do
      get :send_notifications
    end
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :products, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :posts, except: :show do
    resources :pictures do
      member do
        get :make_master
      end
    end
  end
  resources :post_categories
  resources :public_products, only: :show, path: :produtos
  resources :public_post_categories, only: :show, path: 'posts-por-categoria'
  resources :public_races, only: [:index, :show], path: 'provas', path_names: {calendar: 'calendario', last: 'ultimos-resultados', race_organization: 'organize-sua-prova', send_contact: 'enviar-mensagem'} do
    collection do
      get :calendar
      get :last
      get :race_organization
      post :send_contact
    end
  end
  resources :public_teams, only: [:index, :show], path: 'equipes', path_names: {special: 'oficiais'} do
    collection do
      get :special
    end
  end
  get 'posts/:id' => 'public_posts#show', as: :public_post
  resources :public_robberies, path: 'furtos', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }
  resources :public_suspicions, path: 'suspeitas', path_names: { new: 'registrar', edit: 'atualizar', destroy: 'apagar' }

  get 'minha-conta' => 'my_account#index', as: :my_account
  put 'atualizar-minha-conta' => 'my_account#update', as: :update_my_account

end

app/controllers/my_account_controller.rb
class MyAccountController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def update
    if current_user.update_without_password(user_params)
      redirect_to :back, notice: 'Suas informações foram salvas com sucesso'
    else
      flash[:notice] = 'Erro ao salvar sua informações verifique os campos abaixo'
      render :index
    end
  end

  private
    def user_params
      params[:user].permit(:name, :info, :photo, :zipcode, :address, :state, :city, :specialty,
        :facebook_url, :send_races)
    end
end

app/views/my_account/_edit_my_data.erb
<p><small><%= t('.text').html_safe %></small></p>

<%= simple_form_for(current_user, url: update_my_account_path, html: { method: :put, class: 'form-horizontal' }) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.input :name, required: true, autofocus: true %>
    </div>
    <div class="col-sm-12">
      <%= f.input :email, required: true %>
    </div>
    <div class="col-sm-12">
      <%= f.input :photo, as: :file %>
    </div>
    <% if f.object.photo_file_name %>
    <div>
      <%= image_tag f.object.photo.url(:thumb) %>
    </div>
    <% end -%>
    <div class="col-sm-12">
      <%= f.input :info, input_html: {rows: 3} %>
    </div>
    <div class="col-sm-12">
      <%= f.input :specialty %>
    </div>
    <div class="col-sm-12">
      <%= f.input :facebook_url %>
    </div>
    <div class="col-sm-12">
      <%= f.input :zipcode %>
    </div>
    <div class="col-sm-12">
      <%= f.input :state %>
    </div>
    <div class="col-sm-12">
      <%= f.input :city %>
    </div>
    <div class="col-sm-12">
      <%= f.input :address %>
    </div>
    <div class="col-sm-12">
      <%= f.input :send_races %>
    </div>
  </div>

    <%= f.submit t('.save'), class: 'btn btn-primary' %>
<% end %>

app/views/my_account/_edit_team.erb
<h2><%= t('soon').html_safe %></h2>

app/views/my_account/_robberies.erb
<h2><%= t('soon').html_safe %></h2>

app/views/my_account/index.html.erb
<!--Background Image title-->
<section class="bg-title">
  <!-- <img src="img/titles-zones/title-zone-02.jpg" alt=""> -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row text-content paddings center">
      <div class="col-md-12">
        <h2><%= t('.title') %></h2>
      </div>
    </div>
  </div>
</section>
<!--Background Image title-->
<section class="container padding-bottom top-mini">
  <div role="tabpanel" class="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#edit_my_data" aria-controls="edit_my_data" role="tab" data-toggle="tab"><%= t('my_account.edit_my_data.title') %></a></li>
      <li role="presentation"><a href="#robberies" aria-controls="robberies" role="tab" data-toggle="tab"><%= t('my_account.robberies.title') %></a></li>
      <li role="presentation"><a href="#edit_team" aria-controls="edit_team" role="tab" data-toggle="tab"><%= t('my_account.edit_team.title') %></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="edit_my_data">
        <%= render 'edit_my_data' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="robberies">
        <%= render 'robberies' %>
      </div>
      <div role="tabpanel" class="tab-pane" id="edit_team">
        <%= render 'edit_team' %>
      </div>
    </div>
  </div>
</section>